name: maxspeak
description: Affordable text-to-speech reader app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  cupertino_icons: ^1.0.6
  
  # State Management - Using Riverpod for better performance and testing
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.5
  
  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.5
  
  # Local Storage - Using Hive for better performance with PDFs
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  
  # PDF Handling
  pdfx: ^2.6.0  # PDF.js based Flutter plugin
  
  # File Management
  file_picker: ^6.1.1
  share_plus: ^7.2.2
  
  # TTS
  flutter_tts: ^3.8.5  # Native TTS fallback
  
  # Navigation
  go_router: ^13.2.0
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  
  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.3.3
  intl: ^0.19.0
  
  # Network (for future cloud sync)
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  injectable_generator: ^2.4.2
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
